03/01/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

using AdventureWorks;
using _01.Models;

namespace _01.Controllers
{
    public class SalesController : Controller
    {


        #region public ActionResult Index()
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region public ActionResult GetSalesPersons([DataSourceRequest]DataSourceRequest request)
        public ActionResult GetSalesPersons([DataSourceRequest]DataSourceRequest request)
        {

            return Json(SalesPersonViewModel.GetSalesPeople(request), JsonRequestBehavior.AllowGet);
            
        }
        #endregion



        #region public ActionResult Orders(int? id)

        public ActionResult Orders(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TempData["SalesPersonSelectedID"] = id;
            return View("Orders");
            
        }
        #endregion

        #region public ActionResult GetOrdersForSalesPerson([DataSourceRequest]DataSourceRequest request)

        public ActionResult GetOrdersForSalesPerson([DataSourceRequest]DataSourceRequest request)
        {
            int SalesPersonID = 0;

            if (TempData["SalesPersonSelectedID"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (int.TryParse(TempData["SalesPersonSelectedID"].ToString(), out SalesPersonID) == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                return Json(SalesOrderViewModel.GetOrdersBySalesPerson(SalesPersonID, request), JsonRequestBehavior.AllowGet);
            }
        }

        #endregion



    }
}

03/01/Views/Sales/AddressBillTo.cshtml
@model _01.Models.SalesOrderViewModel

@{
    ViewBag.Title = "Billing To Address Information Details";
}

<h2>Billing To Address Information Details</h2>

<div >
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.BillToAddressLine1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillToAddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillToAddressLine2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillToAddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillToCity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillToCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillToStateProvince)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillToStateProvince)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillToPostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillToPostalCode)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Back to Order List", "Orders", new { id = Model.SalesPersonID })
</p>

03/01/Views/Sales/AddressShipTo.cshtml
@model _01.Models.SalesOrderViewModel

@{
    ViewBag.Title = "Shipping To Address Information Details";
}


<h2>Shipping To Address Information Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.ShipToAddressLine1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipToAddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipToAddressLine2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipToAddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipToCity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipToCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipToStateProvince)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipToStateProvince)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipToPostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipToPostalCode)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Back to Order List", "Orders", new { id = Model.SalesPersonID })
</p>

03/01/Views/Sales/Details.cshtml
@model _01.Models.SalesPersonViewModel

@{
    ViewBag.Title = "Sales Person Details";
}

<h2>Sales Person Details</h2>



<div>

    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumberType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailPromotion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailPromotion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateProvinceName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StateProvinceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryRegionName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CountryRegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TerritoryName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TerritoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TerritoryGroup)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TerritoryGroup)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

03/01/Views/Sales/Index.cshtml
<style type="text/css">
    #details-container {
        padding: 10px;
    }

        #details-container h2 {
            margin: 0;
        }

        #details-container em {
            color: #8c8c8c;
        }

        #details-container dt {
            margin: 0;
            display: inline;
        }
</style>




<script type="text/x-kendo-template" id="template">
    <div id="details-container">
        <h2>#= FirstName # #= MiddleName # #= LastName #</h2>
        <dl class="dl-horizontal">
            <dt>Phone Number: </dt> 
            <dd>#= PhoneNumber #</dd>
            <dt>Phone Number Type: </dt>
            <dd>#= PhoneNumberType #</dd>
            <dt>E-Mail Address: </dt>
            <dd>#= EmailAddress #</dd>
            <dt>E-Mail Promotion: </dt>
            <dd>#= EmailPromotion #</dd>
            <dt>Address Line One: </dt>
            <dd>#= AddressLine1 #</dd>
            <dt>Address Line Two: </dt>
            <dd>#= AddressLine2 #</dd>
            <dt>City: </dt>
            <dd>#= City #</dd>
            <dt>State Or Province: </dt>
            <dd>#= StateProvinceName #</dd>
            <dt>Postal Code: </dt>
            <dd>#= PostalCode #</dd>
            <dt>Country Or Region: </dt>
            <dd>#= CountryRegionName #</dd>
        </dl>
    </div>
</script>


<script type="text/javascript">
    var detailsTemplate = kendo.template($("#template").html());

    function showDetails(e) {
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var wnd = $("#Details").data("kendoWindow");

        wnd.content(detailsTemplate(dataItem));
        wnd.center().open();
    }
</script>

<script type="text/javascript">

    function showOrders(e) {
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        window.location.href = '@Url.Action("Orders", "Sales")/' + dataItem.BusinessEntityID;

    }


</script>





<div class="demo-section">
    <div id="gridWrapp" class="k-content">

        @(Html.Kendo().Grid<_01.Models.SalesPersonViewModel>()
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Bound(person => person.FirstName);
            columns.Bound(person => person.MiddleName);
            columns.Bound(person => person.LastName);
            columns.Bound(person => person.SalesQuota).Format("{0:c2}");
            columns.Bound(person => person.SalesYTD).Format("{0:c2}");
            columns.Bound(person => person.SalesLastYear).Format("{0:c2}");
            columns.Command(command => command.Custom("View Details").Click("showDetails")).Width(240);
            columns.Command(command => command.Custom("View Orders").Click("showOrders")).Width(240);

        })
        .DataSource(dataSource => dataSource
              .Ajax()
              .Read(read => read.Action("GetSalesPersons", "Sales"))
              .PageSize(20)
              .ServerOperation(false)
            )
            .Pageable()
            .Sortable()
            .Filterable()
        )

        @(Html.Kendo().Window().Name("Details")
            .Title("Customer Details")
            .Visible(false)
            .Modal(true)
            .Draggable(true)
            .Width(360)
        )



    </div>
</div>

03/01/Views/Sales/OrderDetails.cshtml
@model _01.Models.SalesOrderViewModel

@{
    ViewBag.Title = "Sales Order Details";
}

<h2>Sales Order Details</h2>

<div>
    <hr />
    <h4>Customer Name</h4>
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.CustomerTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerMiddleName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerMiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerSuffix)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerSuffix)
        </dd>
    </dl>

    <hr />

    <h4>Order Dates and Status</h4>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    <hr />

    <h4>Order Dollar and Money Amounts</h4>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.SubTotalString)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubTotalString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaxAmtString)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxAmtString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FreightString)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FreightString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalDueString)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalDueString)
        </dd>

    </dl>
</div>


<p>
    @Html.ActionLink("Back to Order List", "Orders", new { id = Model.SalesPersonID })
</p>

03/01/Views/Sales/Orders.cshtml
<style type="text/css">
    #details-container {
        padding: 10px;
    }

        #details-container h2 {
            margin: 0;
        }

        #details-container em {
            color: #8c8c8c;
        }

        #details-container dt {
            margin: 0;
            display: inline;
        }
</style>

<script type="text/x-kendo-template" id="template">
    <div id="details-container">
        <h4> #= SalesOrderNumber # </h4>
        <h4> #= AccountNumber # </h4>
        <h4>#= PurchaseOrderNumber #</h4>
        <dl class="dl-horizontal">
            <dt>Customer Title: </dt>
            <dd>#= CustomerTitle #</dd>
            <dt>Customer First Name: </dt>
            <dd>#= CustomerFirstName #</dd>
            <dt>Customer Middle Name: </dt>
            <dd>#= CustomerMiddleName #</dd>
            <dt>Customer Last Name: </dt>
            <dd>#= CustomerLastName #</dd>
            <dt>Customer Suffix: </dt>
            <dd>#= CustomerSuffix #</dd>


            <dt>Order Date: </dt>
            <dd>#= OrderDate #</dd>
            <dt>Due Date: </dt>
            <dd>#= DueDate #</dd>
            <dt>Ship Date: </dt>
            <dd>#= ShipDate #</dd>
            <dt>Status: </dt>
            <dd>#= Status #</dd>


            <dt>Sub Total Amount: </dt>
            <dd>#= SubTotalString #</dd>
            <dt>Tax Amount: </dt>
            <dd>#= TaxAmtString #</dd>
            <dt>Freight Amount: </dt>
            <dd>#= FreightString #</dd>
            <dt>Total Due Amount: </dt>
            <dd>#= TotalDueString #</dd>



        </dl>
    </div>
</script>



<script type="text/javascript">
    var detailsTemplate = kendo.template($("#template").html());

    function showDetails(e) {
        console.log("The showDetails() method is starting ... ");
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var wnd = $("#Details").data("kendoWindow");


        $.each(dataItem, function (key, value) {
            console.log(key, value);
        });


        wnd.content(detailsTemplate(dataItem));
        wnd.center().open();
    }

</script>

@(Html.Kendo().Window().Name("Details")
            .Title("Customer Details")
            .Visible(false)
            .Modal(true)
            .Draggable(true)
            .Width(360)
)

<div class="demo-section">
    <div id="gridWrapp" class="k-content">



    </div>
</div>

<div class="demo-section">
    <div id="gridWrapp" class="k-content">

        @(Html.Kendo().Grid<_01.Models.SalesOrderViewModel>()
            .Name("Grid")
            .DataSource(dataSource => dataSource
                .Ajax()
                .Read(read => read.Action("GetOrdersForSalesPerson", "Sales"))
                .PageSize(20)
                .ServerOperation(false))
            .Columns(columns =>
            {
                columns.Bound(order => order.SalesOrderNumber);
                columns.Bound(order => order.AccountNumber);
                columns.Bound(order => order.PurchaseOrderNumber);
                columns.Command(command => command.Custom("Order Details").Click("showDetails")).Width(240);
            })
            .Pageable(pageable => pageable
                .Refresh(true)
                .PageSizes(true)
                .ButtonCount(5))

        )

    </div>
</div>